// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeIApm1gHNugbDTBsyYb6f6YUeHGnuLlk',
    appId: '1:1031509754392:android:fcea675f2c27f1913c796d',
    messagingSenderId: '1031509754392',
    projectId: 'signin-aaf21',
    storageBucket: 'signin-aaf21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJwcFL2HJdLsE5jl73Ha9X1wE8_82mj0k',
    appId: '1:1031509754392:ios:b6a10c6b772875db3c796d',
    messagingSenderId: '1031509754392',
    projectId: 'signin-aaf21',
    storageBucket: 'signin-aaf21.firebasestorage.app',
    androidClientId: '1031509754392-980hvrbfhbu5sminqcig0rgn002rud95.apps.googleusercontent.com',
    iosClientId: '1031509754392-vcldrphsfoms82ngh6m0rtiu1d165c9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.interview',
  );

}